///
/// Fiesty (C) 2014 by Jeffery A Esposito
///
/// wrapper of the generated code, includes "generated.cpp" which should be 
/// generated by the "fiesty gen >generated.cpp"
///
#include "fiesty.h"
#include "bitboard.h"
#include "gen.h"

//
//  Note:  If you are working on adding new "generate" code, you might want 
//  to comment the include below out until you get it working correctly
//
#define FIESTYGEN
#if !defined( FIESTYGEN )
#include "gen.out"
#endif

