///
/// Fiesty (C) 2014 by Jeffery A Esposito
///
/// wrapper of the generated code, includes "generated.cpp" which should be 
/// generated by the "fiesty gen >generated.cpp"
///
#include "fiesty.h"
#include "bitboard.h"
#include "gen.h"

//
// To run a gen, comment out this line of code.
//
#include "gen.out"

