///
/// Fiesty (C) 2014 by Jeffery A Esposito
///
/// wrapper of the generated code, includes "generated.cpp" which should be 
/// generated by the "fiesty gen >generated.cpp"
///
#include "fiesty.h"
#include "bitboard.h"
#include "gen.h"

//
//  Note:  If you are working on adding new "generate" code, you might want 
//  to comment the include below out until you get it working correctly
//
#define FIESTYGEN
#if !defined( FIESTYGEN )
#include "gen.out"
#endif

///
/// Generates source code for various bitboards, such as move sets and 
/// magics.
///
void CGen::generate()
{
    genKnightMoveSet();
}

///
/// Generates source code for the knight moves
///
void CGen::genKnightMoveSet()
{
    std::cout << "static const YBitBoard CGen::bbKnightMoveSet[CSqix::kNumSquares] = {";
    for ( U8 sq =  0; sq < CSqix::kNumSquares; sq++ )
    {
        CSqix sqix( sq );
        I8 r = I8( sqix.getRank().get() );
        I8 f = I8( sqix.getFile().get() );
        std::cout << "\n    /* " << sqix.asAbbr() << " */ ";
        CBitBoard bb( 0ULL );
        bb.setIfValid( r + 2, f + 1 );
        bb.setIfValid( r + 2, f - 1 );
        bb.setIfValid( r - 2, f + 1 );
        bb.setIfValid( r - 2, f - 1 );
        bb.setIfValid( r + 1, f + 2 );
        bb.setIfValid( r + 1, f - 2 );
        bb.setIfValid( r - 1, f + 2 );
        bb.setIfValid( r - 1, f - 2 );
        std::cout << bb.asAbbr() << "ULL";
        if( sq != CSqix::kNumSquares - 1 ) 
            std::cout << ",";
    }
    std::cout << " };\n" << std::flush;
}
